### ISSUE TITLE
Fresh git clone crashing when downloading input files from gdrive

### ISSUE THREAD

**Issue by gotten** [vortex-exoplanet/HEEPS#33]
I'm trying to run a fresh git clone from the repository but it crashes on "file is not a zip file" when downloading the input files. I'm assuming the website/API is just returning some other error that isn't caught. Did the input_file .zip stored on the gdrive change it's ID or did the gdrive API method change ? (I remember it was working in June 2021 and I still have those input_files but I moved them out of the way to see if there were any new files)

```
Downloading input files from Google Drive to
'/home/gotten/heeps_metis/input_files/'

Traceback (most recent call last):
  File "run_heeps.py", line 68, in <module>
    run_heeps()
  File "run_heeps.py", line 13, in run_heeps
    conf = heeps.config.read_config(verbose=False)
  File "/home/gotten/temp/HEEPS2/heeps/config/read_config.py", line 191, in read_config
    extract_zip(conf['gdrive_id'], conf['dir_input'])
  File "/home/gotten/temp/HEEPS2/heeps/util/download_from_gdrive.py", line 13, in extract_zip
    with zipfile.ZipFile(zipfilename,'r') as zip_ref:
  File "/home/gotten/anaconda3/envs/heeps/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/gotten/anaconda3/envs/heeps/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by gotten** [comment]
The download works again, thanks for the quick fix.
